version: "3.0"

services:
  eurekaserver:
    build: discovery-service
    container_name: eurekaserver
    image: eurekaserver
    networks:
      - eureka-server
    depends_on:
      - fluent-bit
    ports:
      - "8761:8761"   
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24225
        tag: eurekaserver
  microservice-gestion-compte:
    build: gestionCompte
    container_name: gestionCompte
  #  network_mode: host 
    image: msgestioncompte
    ports:
      - "8081:8081"
    networks:
      - eureka-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka
    depends_on:
      - eurekaserver
      - fluent-bit
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24225
        tag: gestionCompte
  microservice-gestion-user:
    build: user-service
    container_name: user-service
  #  network_mode: host 
    image: msgestionusers
    ports:
      - "8082:8082"
    networks:
      - eureka-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka
    depends_on:
      - eurekaserver 
      - fluent-bit
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24225
        tag: user-service
  microservice-getway:
    build: gateway-service
    container_name: gateway-service
  #  network_mode: host 
    image: gateway-service
    ports:
      - "8762:8762"
    networks:
      - eureka-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka
    depends_on:
      - eurekaserver
      - fluent-bit
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24225
        tag: gateway-service 
  currency-service:
    build: currency-service
    depends_on:
      - eurekaserver
      - postgresql
      - fluent-bit
    container_name: currency-service
    privileged: true
    volumes:
      - my_volume:/app
    ports:
      - "8989:8989"
    networks:
      - app
      - eureka-server
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:24225
    #     tag: currency-service
#fluentbit service      
  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:latest
    container_name: fluent-bit-spring-app
    privileged: true
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - my_volume:/app
    ports:
      - "24225:24224"
      - "24225:24224/udp"
    networks:
      - loki
  postgresql:
    container_name: postgresql
    image: postgres:14-alpine
    volumes:
      - my_volume:/var/lib/database
      - "./scripts:/docker-entrypoint-initdb.d/"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: currency
    ports:
      - "5432:5432"
    networks:
      - app
    command: --max_prepared_transactions=110
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24225
        tag: postgresql
networks:
  loki:
    external: true
  app:
    external: true
  eureka-server:
    driver: bridge
volumes:
  my_volume:
