server:
  port: 8762

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: credit
          uri: lb://credit-service
          predicates:
            - Path=/api/simulator/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: rendezVous
          uri: lb://rendezVous-service
          predicates:
            - Path=/api/GestionRendezVous/**
        - id: requestCredit
          uri: lb://credit-service
          predicates:
            - Path=/api/creditrequests/**
        - id: gestionCompte
          uri: lb://compte-service
          predicates:
            - Path=/api/GestionCompte/**
        - id: currency-service
          uri: lb://currency-service
          predicates:
            - Path=/api/converter/**
        
eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  