version: '3.0'

services:
  postgres-14.3:
    image: "postgres:14.3-alpine"
    container_name: "postgres14ms"
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres+123
      POSTGRES_DB: cartecredit
    ports:
      - "5432:5432"
    volumes:
      - "./scripts:/docker-entrypoint-initdb.d/"
    command: ["--max_prepared_transactions=180", "--max_connections=500"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 10
    networks:
      - eureka-server

  carte-bancaire-ms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carte-bancaire-ms
    image: carte-bancaire-ms
    ports:
      - "5000:5000"
    depends_on:
      - postgres-14.3
    networks:
      - eureka-server

networks:
  eureka-server:
    driver: bridge
